package version

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

// The repository-root `server.json` is the metadata published to the official
// MCP Registry. Nothing in a normal build reads it, which is exactly why it
// needs a test: it is only exercised during a release, and a mistake in it is
// discovered by a tag that has already been cut.
//
// Every assertion here corresponds to a way the registry rejects a publish, and
// the description limit is in the list because it is the one that is **not** in
// the published JSON schema -- the first integration run found it by being
// answered `422`.
func TestPublishedServerMetadata(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "server.json"))
	if err != nil {
		t.Fatalf("read server.json: %v", err)
	}

	var document struct {
		Schema      string `json:"$schema"`
		Name        string `json:"name"`
		Title       string `json:"title"`
		Description string `json:"description"`
		Version     string `json:"version"`
		WebsiteURL  string `json:"websiteUrl"`
		Repository  struct {
			URL    string `json:"url"`
			Source string `json:"source"`
		} `json:"repository"`
		Packages json.RawMessage `json:"packages"`
	}
	if err := json.Unmarshal(raw, &document); err != nil {
		t.Fatalf("parse server.json: %v", err)
	}

	// GitHub authentication only grants the namespace of the repository doing
	// the publishing, so a name that does not match is rejected outright.
	const wantName = "io.github.Luqueee/kivgraph"
	if document.Name != wantName {
		t.Errorf("name = %q, want %q: the namespace must match the publishing repository", document.Name, wantName)
	}

	if length := len([]rune(document.Description)); length > 100 {
		t.Errorf("description is %d characters, want at most 100: the registry answers 422 above that, and the JSON schema does not say so", length)
	}
	if document.Description == "" {
		t.Error("description is required")
	}

	if !regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+$`).MatchString(document.Version) {
		t.Errorf("version = %q, want X.Y.Z", document.Version)
	}

	// The packages carry a `fileSha256` of an artifact that does not exist
	// until the release is built, so they are generated by
	// `scripts/build-server-json.sh` and never committed. A committed array
	// would be a checksum nobody verified, and the generator refuses to run
	// against a template that has one.
	if document.Packages != nil {
		t.Error("server.json must not commit a packages array; scripts/build-server-json.sh adds it from the artifacts actually being uploaded")
	}

	if document.Schema == "" {
		t.Error("$schema is required so the file validates without the publisher")
	}
	if document.Repository.URL != "https://github.com/Luqueee/kivgraph" || document.Repository.Source != "github" {
		t.Errorf("repository = %+v, want the GitHub repository this publishes from", document.Repository)
	}
	if document.WebsiteURL != "https://kivgraph.dev" {
		t.Errorf("websiteUrl = %q, want https://kivgraph.dev", document.WebsiteURL)
	}
}
