// Kivgraph synthetic benchmark schema, version 001.
// Stable keys are generated by Kivgraph; no key is inferred from a display name.

CREATE NODE TABLE IF NOT EXISTS Repository(
    stable_key STRING PRIMARY KEY,
    name STRING,
    path STRING,
    language STRING
);

CREATE NODE TABLE IF NOT EXISTS File(
    stable_key STRING PRIMARY KEY,
    repository_key STRING,
    path STRING,
    content_hash STRING,
    language STRING
);

CREATE NODE TABLE IF NOT EXISTS Symbol(
    stable_key STRING PRIMARY KEY,
    repository_key STRING,
    file_key STRING,
    name STRING,
    qualified_name STRING,
    kind STRING,
    signature STRING,
    start_line INT64,
    end_line INT64
);

CREATE REL TABLE IF NOT EXISTS CONTAINS(
    FROM Repository TO File,
    relation_kind STRING
);

CREATE REL TABLE IF NOT EXISTS DEFINES(
    FROM File TO Symbol,
    relation_kind STRING
);

CREATE REL TABLE IF NOT EXISTS REFERENCES(
    FROM Symbol TO Symbol,
    evidence_kind STRING,
    source_file_key STRING,
    target_file_key STRING
);

CREATE REL TABLE IF NOT EXISTS CALLS_DIRECT(
    FROM Symbol TO Symbol,
    evidence_kind STRING,
    source_file_key STRING,
    target_file_key STRING
);
