// Ladygraph canonical graph schema, version 002.
// Generated from internal/storage/ladybug.CanonicalSchemaStatements.
// Every primary key is a durable Ladygraph key; no key is inferred from a
// display name and none is generated by the database.

CREATE NODE TABLE IF NOT EXISTS GraphMetadata(
    key STRING PRIMARY KEY,
    value STRING
);

CREATE NODE TABLE IF NOT EXISTS Repository(
    stable_key STRING PRIMARY KEY,
    name STRING,
    root_path STRING,
    commit STRING,
    branch STRING,
    dirty BOOL,
    languages STRING
);

CREATE NODE TABLE IF NOT EXISTS Package(
    stable_key STRING PRIMARY KEY,
    repository_key STRING,
    language STRING,
    name STRING,
    version STRING,
    root_path STRING,
    manifest_path STRING,
    container STRING
);

CREATE NODE TABLE IF NOT EXISTS File(
    stable_key STRING PRIMARY KEY,
    repository_key STRING,
    package_key STRING,
    path STRING,
    language STRING,
    content_hash STRING,
    generated BOOL
);

CREATE NODE TABLE IF NOT EXISTS Symbol(
    stable_key STRING PRIMARY KEY,
    canonical_identity STRING,
    repository_key STRING,
    package_key STRING,
    file_key STRING,
    language STRING,
    name STRING,
    qualified_name STRING,
    kind STRING,
    exported BOOL,
    signature STRING,
    start_line INT64,
    start_column INT64,
    start_offset INT64,
    end_line INT64,
    end_offset INT64
);

CREATE NODE TABLE IF NOT EXISTS Evidence(
    stable_key STRING PRIMARY KEY,
    repository_key STRING,
    file_key STRING,
    start_line INT64,
    start_column INT64,
    start_offset INT64,
    end_offset INT64,
    text STRING
);

CREATE NODE TABLE IF NOT EXISTS UnresolvedReference(
    stable_key STRING PRIMARY KEY,
    repository_key STRING,
    file_key STRING,
    language STRING,
    source_symbol_key STRING,
    requested_package STRING,
    requested_symbol STRING,
    reason STRING,
    detail STRING,
    start_line INT64,
    start_column INT64,
    start_offset INT64
);

CREATE REL TABLE IF NOT EXISTS CONTAINS_PACKAGE(
    FROM Repository TO Package,
    confidence STRING,
    provenance STRING,
    ONE_MANY
);

CREATE REL TABLE IF NOT EXISTS CONTAINS_FILE(
    FROM Package TO File,
    confidence STRING,
    provenance STRING,
    ONE_MANY
);

CREATE REL TABLE IF NOT EXISTS DEFINES(
    FROM File TO Symbol,
    confidence STRING,
    provenance STRING,
    ONE_MANY
);

CREATE REL TABLE IF NOT EXISTS OBSERVED_IN(
    FROM Evidence TO File,
    MANY_ONE
);

CREATE REL TABLE IF NOT EXISTS REPORTS_UNRESOLVED(
    FROM Repository TO UnresolvedReference,
    ONE_MANY
);

CREATE REL TABLE IF NOT EXISTS PACKAGE_DEPENDS_ON(
    FROM Package TO Package,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS MODULE_DEPENDS_ON(
    FROM Package TO Package,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS IMPORTS_SYMBOL(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS EXPORTS(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS REEXPORTS(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS REFERENCES(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS CALLS_DIRECT(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS PASSES_AS_CALLBACK(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS ASSIGNS_FUNCTION(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS RETURNS_FUNCTION(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS TYPE_USES(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS IMPLEMENTS(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS EXTENDS(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS EMBEDS(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);

CREATE REL TABLE IF NOT EXISTS OVERRIDES(
    FROM Symbol TO Symbol,
    confidence STRING,
    provenance STRING,
    evidence_key STRING,
    source_snapshot INT64,
    resolver_version STRING,
    MANY_MANY
);
